name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop linting

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.6
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop

  tests:
    needs: rubocop
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby_version }}

    strategy:
      matrix:
        ruby_version: [2.7.6, 3.0.4, 3.1.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rspec
